---
- name: Update and upgrade apt packages
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Ensure nginx is at the latest version
  apt:
    name: nginx 
    state: latest
- name: Make sure Nginx is running
  systemd:
    state: started
    name: nginx
- name: Copy webapp to /var/www/html
  ansible.builtin.copy:
    src: "../../app/index.html"
    dest: "/var/www/html"
    owner: ubuntu
    group: ubuntu
    mode: "644"