---
- name: Ansible Copy Example Local to Remote
  hosts: nginx
  tasks:
    - name: Copying file with playbook
      become: true 
      copy:
        src: "./app/index.html"
        dest: /var/www/html
        owner: "ubuntu"
        group: "ubuntu"        
        mode: 0644